// Comprehensive mock data for Sierra Soul demo

export const mockUsers = [
  {
    id: "1",
    name: "Amara Okafor",
    username: "amara_explorer",
    email: "amara@example.com",
    avatar: "/placeholder.svg?height=100&width=100&text=AO",
    bio: "Travel photographer capturing the beauty of Africa 📸 | Lagos, Nigeria 🇳🇬",
    location: "Lagos, Nigeria",
    followers: 2340,
    following: 890,
    verified: true,
    joinDate: "March 2023",
  },
  {
    id: "2",
    name: "Kwame Asante",
    username: "kwame_arts",
    email: "kwame@example.com",
    avatar: "/placeholder.svg?height=100&width=100&text=KA",
    bio: "Traditional sculptor preserving Akan heritage through art 🎨 | Kumasi, Ghana 🇬🇭",
    location: "Kumasi, Ghana",
    followers: 1890,
    following: 456,
    verified: true,
    joinDate: "January 2023",
  },
  {
    id: "3",
    name: "Zara Mwangi",
    username: "zara_safari",
    email: "zara@example.com",
    avatar: "/placeholder.svg?height=100&width=100&text=ZM",
    bio: "Safari guide & wildlife conservationist 🦁 | Nairobi, Kenya 🇰🇪",
    location: "Nairobi, Kenya",
    followers: 3200,
    following: 1200,
    verified: true,
    joinDate: "June 2022",
  },
]

export const mockPosts = [
  {
    id: "1",
    user: {
      name: "Amara Okafor",
      avatar: "/placeholder.svg?height=40&width=40&text=AO",
      username: "amara_explorer",
    },
    content:
      "Just witnessed the most incredible sunset over the Sahara Desert! 🌅 The colors were absolutely breathtaking - from deep oranges to purple hues painting the endless dunes. This is why I love exploring our beautiful continent. Every sunset tells a different story here. #SaharaDesert #AfricanSunset #TravelAfrica #Morocco",
    images: [
      "/placeholder.svg?height=400&width=600&text=Sahara+Sunset+1",
      "/placeholder.svg?height=400&width=600&text=Sahara+Sunset+2",
      "/placeholder.svg?height=400&width=600&text=Desert+Dunes",
    ],
    likes: 1247,
    comments: 89,
    shares: 34,
    timestamp: "2 hours ago",
    location: "Sahara Desert, Morocco",
    isLiked: false,
    isSaved: false,
  },
  {
    id: "2",
    user: {
      name: "Kwame Asante",
      avatar: "/placeholder.svg?height=40&width=40&text=KA",
      username: "kwame_arts",
    },
    content:
      "Finished my latest sculpture inspired by traditional Akan Adinkra symbols! 🎨 This piece represents 'Sankofa' - the wisdom of learning from the past. Each carving tells a story of our ancestors and their profound wisdom. Art is truly the bridge between past and present, connecting generations through shared heritage. ✨ #AkanArt #Adinkra #AfricanSculpture #Heritage",
    images: ["/placeholder.svg?height=400&width=600&text=Akan+Sculpture"],
    likes: 892,
    comments: 156,
    shares: 67,
    timestamp: "5 hours ago",
    location: "Kumasi, Ghana",
    isLiked: true,
    isSaved: false,
  },
  {
    id: "3",
    user: {
      name: "Zara Mwangi",
      avatar: "/placeholder.svg?height=40&width=40&text=ZM",
      username: "zara_safari",
    },
    content:
      "Early morning game drive in Maasai Mara and we spotted this magnificent lioness with her cubs! 🦁 Moments like these remind me why wildlife conservation is so crucial. These majestic creatures deserve our protection and respect. Book your safari experience and witness Africa's incredible wildlife firsthand! #MaasaiMara #WildlifeConservation #Safari #Kenya #BigCats",
    images: [
      "/placeholder.svg?height=400&width=600&text=Lioness+Cubs",
      "/placeholder.svg?height=400&width=600&text=Maasai+Mara+Landscape",
    ],
    likes: 2156,
    comments: 234,
    shares: 89,
    timestamp: "8 hours ago",
    location: "Maasai Mara, Kenya",
    isLiked: false,
    isSaved: true,
  },
  {
    id: "4",
    user: {
      name: "Thandiwe Mthembu",
      avatar: "/placeholder.svg?height=40&width=40&text=TM",
      username: "thandiwe_artist",
    },
    content:
      "My latest painting 'Ubuntu Spirit' is now complete! 🎨 This piece explores the interconnectedness of humanity through vibrant colors and flowing forms. Ubuntu teaches us that 'I am because we are' - a philosophy that resonates deeply in our African culture. Available for viewing at my gallery in Cape Town. #Ubuntu #AfricanArt #ContemporaryArt #CapeTown",
    images: ["/placeholder.svg?height=400&width=600&text=Ubuntu+Spirit+Painting"],
    likes: 567,
    comments: 78,
    shares: 23,
    timestamp: "1 day ago",
    location: "Cape Town, South Africa",
    isLiked: false,
    isSaved: false,
  },
  {
    id: "5",
    user: {
      name: "Omar Hassan",
      avatar: "/placeholder.svg?height=40&width=40&text=OH",
      username: "omar_spices",
    },
    content:
      "Fresh berbere spice blend ready for export! 🌶️ Made with the finest Ethiopian chilies, fenugreek, and aromatic spices passed down through generations. This is the secret to authentic Ethiopian cuisine. Now available in our marketplace - bring the taste of Ethiopia to your kitchen! #BerbereSpice #EthiopianCuisine #AuthenticFlavors #Spices",
    images: [
      "/placeholder.svg?height=400&width=600&text=Berbere+Spices",
      "/placeholder.svg?height=400&width=600&text=Spice+Market",
    ],
    likes: 445,
    comments: 67,
    shares: 34,
    timestamp: "1 day ago",
    location: "Addis Ababa, Ethiopia",
    isLiked: true,
    isSaved: false,
  },
]

export const mockStories = [
  {
    id: "1",
    user: {
      name: "Amara",
      avatar: "/placeholder.svg?height=60&width=60&text=AO",
    },
    viewed: false,
    thumbnail: "/placeholder.svg?height=60&width=60&text=Morocco+Story",
  },
  {
    id: "2",
    user: {
      name: "Kwame",
      avatar: "/placeholder.svg?height=60&width=60&text=KA",
    },
    viewed: true,
    thumbnail: "/placeholder.svg?height=60&width=60&text=Art+Story",
  },
  {
    id: "3",
    user: {
      name: "Zara",
      avatar: "/placeholder.svg?height=60&width=60&text=ZM",
    },
    viewed: false,
    thumbnail: "/placeholder.svg?height=60&width=60&text=Safari+Story",
  },
  {
    id: "4",
    user: {
      name: "Thandiwe",
      avatar: "/placeholder.svg?height=60&width=60&text=TM",
    },
    viewed: false,
    thumbnail: "/placeholder.svg?height=60&width=60&text=Gallery+Story",
  },
  {
    id: "5",
    user: {
      name: "Omar",
      avatar: "/placeholder.svg?height=60&width=60&text=OH",
    },
    viewed: true,
    thumbnail: "/placeholder.svg?height=60&width=60&text=Market+Story",
  },
]

export const mockProducts = [
  {
    id: "1",
    name: "Handwoven Kente Cloth - Royal Pattern",
    price: 285,
    image: "/placeholder.svg?height=300&width=300&text=Kente+Cloth",
    seller: {
      name: "Akosua Textiles",
      rating: 4.9,
      id: "seller1",
    },
    location: "Accra, Ghana",
    category: "Clothing & Fashion",
    inStock: true,
    description:
      "Authentic handwoven Kente cloth featuring traditional royal patterns. Each piece tells a story through its intricate designs and vibrant colors.",
    images: [
      "/placeholder.svg?height=400&width=400&text=Kente+Front",
      "/placeholder.svg?height=400&width=400&text=Kente+Detail",
      "/placeholder.svg?height=400&width=400&text=Kente+Pattern",
    ],
    reviews: 47,
    isFavorited: false,
  },
  {
    id: "2",
    name: "Maasai Beaded Jewelry Set - Traditional",
    price: 125,
    image: "/placeholder.svg?height=300&width=300&text=Maasai+Jewelry",
    seller: {
      name: "Nairobi Crafts Collective",
      rating: 4.8,
      id: "seller2",
    },
    location: "Nairobi, Kenya",
    category: "Jewelry & Accessories",
    inStock: true,
    description:
      "Beautiful handcrafted Maasai beaded jewelry set including necklace, bracelet, and earrings. Made by skilled Maasai artisans using traditional techniques.",
    images: [
      "/placeholder.svg?height=400&width=400&text=Jewelry+Set",
      "/placeholder.svg?height=400&width=400&text=Necklace+Detail",
      "/placeholder.svg?height=400&width=400&text=Bracelet+Detail",
    ],
    reviews: 32,
    isFavorited: true,
  },
  {
    id: "3",
    name: "Premium Ethiopian Coffee Beans - Single Origin",
    price: 45,
    image: "/placeholder.svg?height=300&width=300&text=Coffee+Beans",
    seller: {
      name: "Addis Coffee Roasters",
      rating: 4.7,
      id: "seller3",
    },
    location: "Addis Ababa, Ethiopia",
    category: "Food & Beverages",
    inStock: false,
    description:
      "Premium single-origin Ethiopian coffee beans from the highlands of Sidamo. Known for their bright acidity and floral notes.",
    images: [
      "/placeholder.svg?height=400&width=400&text=Coffee+Bag",
      "/placeholder.svg?height=400&width=400&text=Coffee+Beans+Close",
      "/placeholder.svg?height=400&width=400&text=Coffee+Farm",
    ],
    reviews: 89,
    isFavorited: false,
  },
  {
    id: "4",
    name: "Shona Stone Sculpture - Abstract Form",
    price: 450,
    image: "/placeholder.svg?height=300&width=300&text=Stone+Sculpture",
    seller: {
      name: "Zimbabwe Art Gallery",
      rating: 4.9,
      id: "seller4",
    },
    location: "Harare, Zimbabwe",
    category: "Art & Collectibles",
    inStock: true,
    description:
      "Magnificent Shona stone sculpture carved from serpentine stone. This abstract piece represents the harmony between earth and spirit.",
    images: [
      "/placeholder.svg?height=400&width=400&text=Sculpture+Front",
      "/placeholder.svg?height=400&width=400&text=Sculpture+Side",
      "/placeholder.svg?height=400&width=400&text=Stone+Detail",
    ],
    reviews: 23,
    isFavorited: false,
  },
  {
    id: "5",
    name: "Moroccan Argan Oil - Pure & Organic",
    price: 65,
    image: "/placeholder.svg?height=300&width=300&text=Argan+Oil",
    seller: {
      name: "Atlas Mountain Cooperative",
      rating: 4.8,
      id: "seller5",
    },
    location: "Essaouira, Morocco",
    category: "Beauty & Wellness",
    inStock: true,
    description:
      "100% pure organic argan oil extracted from argan nuts by Berber women's cooperatives. Perfect for skin and hair care.",
    images: [
      "/placeholder.svg?height=400&width=400&text=Argan+Oil+Bottle",
      "/placeholder.svg?height=400&width=400&text=Argan+Nuts",
      "/placeholder.svg?height=400&width=400&text=Cooperative+Women",
    ],
    reviews: 156,
    isFavorited: true,
  },
  {
    id: "6",
    name: "Dashiki Shirt - Authentic Print",
    price: 85,
    image: "/placeholder.svg?height=300&width=300&text=Dashiki+Shirt",
    seller: {
      name: "Lagos Fashion House",
      rating: 4.6,
      id: "seller6",
    },
    location: "Lagos, Nigeria",
    category: "Clothing & Fashion",
    inStock: true,
    description:
      "Authentic dashiki shirt with traditional African print. Made from high-quality cotton with intricate embroidered details.",
    images: [
      "/placeholder.svg?height=400&width=400&text=Dashiki+Front",
      "/placeholder.svg?height=400&width=400&text=Dashiki+Back",
      "/placeholder.svg?height=400&width=400&text=Print+Detail",
    ],
    reviews: 78,
    isFavorited: false,
  },
]

export const mockHotels = [
  {
    id: "1",
    name: "Serengeti Safari Lodge",
    image: "/placeholder.svg?height=300&width=500&text=Serengeti+Lodge",
    location: "Serengeti National Park, Tanzania",
    rating: 4.9,
    price: 380,
    amenities: ["WiFi", "Pool", "Safari Tours", "Restaurant", "Spa", "Bar"],
    description:
      "Experience the wild beauty of Serengeti with luxury accommodations overlooking the endless plains. Wake up to the sounds of nature and witness the Great Migration from your private balcony.",
    images: [
      "/placeholder.svg?height=400&width=600&text=Lodge+Exterior",
      "/placeholder.svg?height=400&width=600&text=Safari+Room",
      "/placeholder.svg?height=400&width=600&text=Pool+View",
      "/placeholder.svg?height=400&width=600&text=Restaurant",
    ],
    reviews: 234,
    available: true,
    checkInTime: "3:00 PM",
    checkOutTime: "11:00 AM",
  },
  {
    id: "2",
    name: "Stone Town Heritage Hotel",
    image: "/placeholder.svg?height=300&width=500&text=Stone+Town+Hotel",
    location: "Stone Town, Zanzibar",
    rating: 4.6,
    price: 180,
    amenities: ["WiFi", "AC", "Rooftop Terrace", "Cultural Tours", "Restaurant"],
    description:
      "Historic boutique hotel in the heart of Stone Town featuring traditional Swahili architecture. Explore the UNESCO World Heritage site right at your doorstep.",
    images: [
      "/placeholder.svg?height=400&width=600&text=Heritage+Building",
      "/placeholder.svg?height=400&width=600&text=Traditional+Room",
      "/placeholder.svg?height=400&width=600&text=Rooftop+Terrace",
      "/placeholder.svg?height=400&width=600&text=Stone+Town+View",
    ],
    reviews: 189,
    available: true,
    checkInTime: "2:00 PM",
    checkOutTime: "12:00 PM",
  },
  {
    id: "3",
    name: "Cape Town Boutique Hotel",
    image: "/placeholder.svg?height=300&width=500&text=Cape+Town+Hotel",
    location: "Cape Town, South Africa",
    rating: 4.8,
    price: 220,
    amenities: ["WiFi", "Pool", "Gym", "Wine Cellar", "Concierge", "Valet"],
    description:
      "Elegant boutique hotel with stunning views of Table Mountain. Located in the vibrant V&A Waterfront with easy access to attractions and restaurants.",
    images: [
      "/placeholder.svg?height=400&width=600&text=Hotel+Exterior",
      "/placeholder.svg?height=400&width=600&text=Mountain+View+Room",
      "/placeholder.svg?height=400&width=600&text=Hotel+Pool",
      "/placeholder.svg?height=400&width=600&text=Wine+Cellar",
    ],
    reviews: 312,
    available: true,
    checkInTime: "3:00 PM",
    checkOutTime: "11:00 AM",
  },
  {
    id: "4",
    name: "Marrakech Riad Oasis",
    image: "/placeholder.svg?height=300&width=500&text=Marrakech+Riad",
    location: "Marrakech, Morocco",
    rating: 4.7,
    price: 160,
    amenities: ["WiFi", "Courtyard Pool", "Hammam", "Rooftop Terrace", "Traditional Breakfast"],
    description:
      "Authentic Moroccan riad with beautiful courtyard and traditional architecture. Experience the magic of Marrakech in this peaceful oasis.",
    images: [
      "/placeholder.svg?height=400&width=600&text=Riad+Courtyard",
      "/placeholder.svg?height=400&width=600&text=Traditional+Room",
      "/placeholder.svg?height=400&width=600&text=Rooftop+Atlas+View",
      "/placeholder.svg?height=400&width=600&text=Hammam+Spa",
    ],
    reviews: 156,
    available: true,
    checkInTime: "2:00 PM",
    checkOutTime: "12:00 PM",
  },
]

export const mockTours = [
  {
    id: "1",
    name: "Victoria Falls Adventure Package",
    image: "/placeholder.svg?height=300&width=500&text=Victoria+Falls",
    location: "Livingstone, Zambia",
    duration: "3 days, 2 nights",
    price: 650,
    type: "Adventure",
    rating: 4.9,
    description:
      "Experience the thundering Victoria Falls with white-water rafting, bungee jumping, helicopter tours, and sunset cruises on the Zambezi River.",
    includes: ["Accommodation", "All Meals", "Activities", "Transport", "Professional Guide"],
    images: [
      "/placeholder.svg?height=400&width=600&text=Victoria+Falls+View",
      "/placeholder.svg?height=400&width=600&text=White+Water+Rafting",
      "/placeholder.svg?height=400&width=600&text=Helicopter+Tour",
      "/placeholder.svg?height=400&width=600&text=Sunset+Cruise",
    ],
    reviews: 89,
    maxGroupSize: 12,
    difficulty: "Moderate",
    available: true,
  },
  {
    id: "2",
    name: "Kilimanjaro Trek - Machame Route",
    image: "/placeholder.svg?height=300&width=500&text=Kilimanjaro+Trek",
    location: "Moshi, Tanzania",
    duration: "7 days, 6 nights",
    price: 1850,
    type: "Trekking",
    rating: 4.8,
    description:
      "Conquer Africa's highest peak via the scenic Machame route. Experience diverse ecosystems from rainforest to arctic conditions at the summit.",
    includes: ["Professional Guide", "Porters", "Equipment", "Park Fees", "Meals", "Accommodation"],
    images: [
      "/placeholder.svg?height=400&width=600&text=Kilimanjaro+Summit",
      "/placeholder.svg?height=400&width=600&text=Machame+Route",
      "/placeholder.svg?height=400&width=600&text=Base+Camp",
      "/placeholder.svg?height=400&width=600&text=Sunrise+Summit",
    ],
    reviews: 156,
    maxGroupSize: 8,
    difficulty: "Challenging",
    available: true,
  },
  {
    id: "3",
    name: "Sahara Desert Camel Trek",
    image: "/placeholder.svg?height=300&width=500&text=Sahara+Camel+Trek",
    location: "Merzouga, Morocco",
    duration: "2 days, 1 night",
    price: 280,
    type: "Cultural",
    rating: 4.7,
    description:
      "Journey into the heart of the Sahara Desert on camelback. Sleep under the stars in a traditional Berber camp and witness unforgettable sunrises and sunsets.",
    includes: ["Camel Trek", "Desert Camp", "Traditional Meals", "Berber Guide", "Sandboarding"],
    images: [
      "/placeholder.svg?height=400&width=600&text=Camel+Caravan",
      "/placeholder.svg?height=400&width=600&text=Desert+Camp",
      "/placeholder.svg?height=400&width=600&text=Sahara+Sunset",
      "/placeholder.svg?height=400&width=600&text=Star+Gazing",
    ],
    reviews: 203,
    maxGroupSize: 15,
    difficulty: "Easy",
    available: true,
  },
  {
    id: "4",
    name: "Gorilla Trekking Experience",
    image: "/placeholder.svg?height=300&width=500&text=Gorilla+Trekking",
    location: "Bwindi Forest, Uganda",
    duration: "4 days, 3 nights",
    price: 1200,
    type: "Wildlife",
    rating: 4.9,
    description:
      "Once-in-a-lifetime opportunity to encounter mountain gorillas in their natural habitat. Trek through pristine rainforest with expert guides.",
    includes: ["Gorilla Permits", "Accommodation", "Meals", "Expert Guide", "Transport"],
    images: [
      "/placeholder.svg?height=400&width=600&text=Mountain+Gorillas",
      "/placeholder.svg?height=400&width=600&text=Bwindi+Forest",
      "/placeholder.svg?height=400&width=600&text=Trekking+Group",
      "/placeholder.svg?height=400&width=600&text=Gorilla+Family",
    ],
    reviews: 78,
    maxGroupSize: 8,
    difficulty: "Moderate",
    available: true,
  },
  {
    id: "5",
    name: "Nile River Source & Cultural Tour",
    image: "/placeholder.svg?height=300&width=500&text=Nile+Source",
    location: "Jinja, Uganda",
    duration: "1 day",
    price: 120,
    type: "Cultural",
    rating: 4.5,
    description:
      "Discover the source of the mighty Nile River and experience local Ugandan culture. Includes boat ride, cultural performances, and local cuisine.",
    includes: ["Boat Ride", "Cultural Show", "Local Lunch", "Guide", "Transport"],
    images: [
      "/placeholder.svg?height=400&width=600&text=Nile+Source",
      "/placeholder.svg?height=400&width=600&text=Boat+Ride",
      "/placeholder.svg?height=400&width=600&text=Cultural+Dance",
      "/placeholder.svg?height=400&width=600&text=Local+Market",
    ],
    reviews: 134,
    maxGroupSize: 20,
    difficulty: "Easy",
    available: true,
  },
]

export const mockArtPieces = [
  {
    id: "1",
    title: "Ubuntu Spirit - The Interconnected Soul",
    artist: "Thandiwe Mthembu",
    artistId: "artist1",
    image: "/placeholder.svg?height=400&width=400&text=Ubuntu+Spirit",
    price: 1250,
    medium: "Acrylic on Canvas",
    dimensions: "80x100 cm",
    available: true,
    description:
      "A vibrant exploration of the Ubuntu philosophy through flowing forms and warm earth tones. This piece celebrates the interconnectedness of humanity.",
    year: 2024,
    category: "Contemporary Painting",
    images: [
      "/placeholder.svg?height=500&width=500&text=Ubuntu+Full",
      "/placeholder.svg?height=500&width=500&text=Ubuntu+Detail1",
      "/placeholder.svg?height=500&width=500&text=Ubuntu+Detail2",
    ],
    likes: 89,
    isLiked: false,
  },
  {
    id: "2",
    title: "Ancestral Wisdom - Adinkra Series",
    artist: "Kofi Mensah",
    artistId: "artist2",
    image: "/placeholder.svg?height=400&width=400&text=Ancestral+Wisdom",
    price: 850,
    medium: "Wood Carving (Mahogany)",
    dimensions: "45x30x20 cm",
    available: true,
    description:
      "Hand-carved mahogany sculpture incorporating traditional Adinkra symbols. Each symbol tells a story of wisdom passed down through generations.",
    year: 2024,
    category: "Traditional Sculpture",
    images: [
      "/placeholder.svg?height=500&width=500&text=Carving+Front",
      "/placeholder.svg?height=500&width=500&text=Carving+Side",
      "/placeholder.svg?height=500&width=500&text=Symbol+Detail",
    ],
    likes: 67,
    isLiked: true,
  },
  {
    id: "3",
    title: "Serengeti Dreams",
    artist: "Amina Kone",
    artistId: "artist3",
    image: "/placeholder.svg?height=400&width=400&text=Serengeti+Dreams",
    price: 950,
    medium: "Oil on Canvas",
    dimensions: "70x90 cm",
    available: true,
    description:
      "Impressionistic landscape capturing the golden hour in the Serengeti. Wildlife silhouettes dance across the canvas in warm, flowing brushstrokes.",
    year: 2023,
    category: "Landscape Painting",
    images: [
      "/placeholder.svg?height=500&width=500&text=Serengeti+Full",
      "/placeholder.svg?height=500&width=500&text=Wildlife+Detail",
      "/placeholder.svg?height=500&width=500&text=Sky+Detail",
    ],
    likes: 134,
    isLiked: false,
  },
  {
    id: "4",
    title: "Masks of Heritage",
    artist: "Bakari Diallo",
    artistId: "artist4",
    image: "/placeholder.svg?height=400&width=400&text=Heritage+Masks",
    price: 650,
    medium: "Mixed Media",
    dimensions: "60x40 cm",
    available: false,
    description:
      "Contemporary interpretation of traditional African masks using mixed media. Explores themes of identity and cultural preservation.",
    year: 2024,
    category: "Mixed Media",
    images: [
      "/placeholder.svg?height=500&width=500&text=Masks+Collage",
      "/placeholder.svg?height=500&width=500&text=Texture+Detail",
      "/placeholder.svg?height=500&width=500&text=Color+Detail",
    ],
    likes: 78,
    isLiked: false,
  },
  {
    id: "5",
    title: "Baobab Guardians",
    artist: "Fatima Al-Rashid",
    artistId: "artist5",
    image: "/placeholder.svg?height=400&width=400&text=Baobab+Guardians",
    price: 1100,
    medium: "Watercolor on Paper",
    dimensions: "50x70 cm",
    available: true,
    description:
      "Majestic baobab trees rendered in delicate watercolors. These ancient guardians of the African landscape stand as symbols of resilience and longevity.",
    year: 2024,
    category: "Watercolor Painting",
    images: [
      "/placeholder.svg?height=500&width=500&text=Baobab+Full",
      "/placeholder.svg?height=500&width=500&text=Tree+Detail",
      "/placeholder.svg?height=500&width=500&text=Landscape+Detail",
    ],
    likes: 156,
    isLiked: true,
  },
]

export const mockArtists = [
  {
    id: "artist1",
    name: "Thandiwe Mthembu",
    avatar: "/placeholder.svg?height=150&width=150&text=TM",
    location: "Cape Town, South Africa",
    specialty: "Contemporary Abstract Painting",
    followers: 3240,
    artworks: 67,
    bio: "Contemporary artist exploring themes of identity, heritage, and human connection through vibrant abstract compositions. My work celebrates the Ubuntu philosophy and the interconnectedness of all beings.",
    education: "MFA Fine Arts, University of Cape Town",
    exhibitions: ["Ubuntu Visions 2024", "African Contemporary Art Fair 2023", "Heritage & Identity Solo Show 2023"],
    awards: ["South African Contemporary Art Award 2023", "Emerging Artist Prize 2022"],
    socialMedia: {
      instagram: "@thandiwe_art",
      website: "www.thandiweart.com",
    },
    verified: true,
  },
  {
    id: "artist2",
    name: "Kofi Mensah",
    avatar: "/placeholder.svg?height=150&width=150&text=KM",
    location: "Kumasi, Ghana",
    specialty: "Traditional Wood Sculpture",
    followers: 2890,
    artworks: 45,
    bio: "Master wood sculptor preserving and reinterpreting traditional Akan cultural symbols through contemporary art. Each piece tells a story of our ancestors and their enduring wisdom.",
    education: "Traditional Apprenticeship, Kumasi Craft Center",
    exhibitions: ["Adinkra Reimagined 2024", "Ghana National Art Exhibition 2023", "Traditional Crafts Revival 2022"],
    awards: ["Ghana National Heritage Award 2023", "Master Craftsman Recognition 2021"],
    socialMedia: {
      instagram: "@kofi_sculptures",
      website: "www.kofimensah.art",
    },
    verified: true,
  },
  {
    id: "artist3",
    name: "Amina Kone",
    avatar: "/placeholder.svg?height=150&width=150&text=AK",
    location: "Bamako, Mali",
    specialty: "Landscape & Wildlife Painting",
    followers: 1950,
    artworks: 38,
    bio: "Landscape painter capturing the raw beauty of African wilderness. My work focuses on conservation themes and the delicate relationship between humans and nature.",
    education: "BA Fine Arts, University of Bamako",
    exhibitions: ["Wild Africa 2024", "Conservation Through Art 2023", "Landscapes of Mali 2022"],
    awards: ["Wildlife Art Conservation Prize 2023"],
    socialMedia: {
      instagram: "@amina_landscapes",
      website: "www.aminakone.art",
    },
    verified: false,
  },
  {
    id: "artist4",
    name: "Bakari Diallo",
    avatar: "/placeholder.svg?height=150&width=150&text=BD",
    location: "Dakar, Senegal",
    specialty: "Mixed Media & Cultural Identity",
    followers: 2156,
    artworks: 52,
    bio: "Mixed media artist exploring cultural identity and heritage preservation. My work bridges traditional African art forms with contemporary expression.",
    education: "MFA Mixed Media, École des Beaux-Arts de Dakar",
    exhibitions: ["Identity Fragments 2024", "Dakar Biennale 2023", "Cultural Crossroads 2022"],
    awards: ["Dakar Biennale Emerging Artist 2023"],
    socialMedia: {
      instagram: "@bakari_mixed",
      website: "www.bakaridiallo.com",
    },
    verified: true,
  },
  {
    id: "artist5",
    name: "Fatima Al-Rashid",
    avatar: "/placeholder.svg?height=150&width=150&text=FR",
    location: "Marrakech, Morocco",
    specialty: "Watercolor & Botanical Art",
    followers: 1678,
    artworks: 41,
    bio: "Watercolor artist specializing in botanical and landscape subjects. My work celebrates the diverse flora and landscapes of North Africa.",
    education: "Diploma in Fine Arts, Marrakech Art Institute",
    exhibitions: ["Desert Blooms 2024", "Moroccan Landscapes 2023", "Botanical Studies 2022"],
    awards: ["Morocco National Art Prize 2022"],
    socialMedia: {
      instagram: "@fatima_watercolors",
      website: "www.fatimaalrashid.art",
    },
    verified: false,
  },
]

export const mockConversations = [
  {
    id: "1",
    participant: {
      name: "Amara Okafor",
      avatar: "/placeholder.svg?height=50&width=50&text=AO",
      online: true,
      lastSeen: "Online now",
    },
    lastMessage:
      "Thanks for the recommendation! The safari was absolutely amazing 🦁 The guides were so knowledgeable!",
    timestamp: "2 min ago",
    unread: 2,
    type: "direct",
  },
  {
    id: "2",
    participant: {
      name: "Serengeti Safari Lodge",
      avatar: "/placeholder.svg?height=50&width=50&text=SSL",
      online: false,
      lastSeen: "1 hour ago",
    },
    lastMessage:
      "Your booking for tomorrow is confirmed. Meet at the main lobby at 6 AM sharp. Don't forget your camera!",
    timestamp: "1 hour ago",
    unread: 0,
    type: "business",
  },
  {
    id: "3",
    participant: {
      name: "Kwame Asante",
      avatar: "/placeholder.svg?height=50&width=50&text=KA",
      online: true,
      lastSeen: "Online now",
    },
    lastMessage: "I'd love to collaborate on that art project! When can we meet to discuss the details?",
    timestamp: "3 hours ago",
    unread: 1,
    type: "direct",
  },
  {
    id: "4",
    participant: {
      name: "Atlas Mountain Tours",
      avatar: "/placeholder.svg?height=50&width=50&text=AMT",
      online: false,
      lastSeen: "5 hours ago",
    },
    lastMessage: "Weather conditions are perfect for the trek. All equipment is ready for pickup tomorrow morning.",
    timestamp: "5 hours ago",
    unread: 0,
    type: "business",
  },
  {
    id: "5",
    participant: {
      name: "Zara Mwangi",
      avatar: "/placeholder.svg?height=50&width=50&text=ZM",
      online: false,
      lastSeen: "2 days ago",
    },
    lastMessage: "The wildlife photography workshop was incredible! Thank you for organizing it 📸",
    timestamp: "2 days ago",
    unread: 0,
    type: "direct",
  },
]

export const mockMessages = [
  {
    id: "1",
    senderId: "other",
    senderName: "Amara Okafor",
    senderAvatar: "/placeholder.svg?height=40&width=40&text=AO",
    content:
      "Hi! I saw your post about the Serengeti safari experience. Could you share more details about the tour operator you used? I'm planning a trip next month!",
    timestamp: "10:30 AM",
    type: "text",
    status: "read",
  },
  {
    id: "2",
    senderId: "me",
    content:
      "Of course! I used Serengeti Safari Lodge and they were absolutely fantastic. Very professional guides with incredible knowledge of wildlife behavior. The accommodation was top-notch too!",
    timestamp: "10:32 AM",
    type: "text",
    status: "read",
  },
  {
    id: "3",
    senderId: "other",
    senderName: "Amara Okafor",
    senderAvatar: "/placeholder.svg?height=40&width=40&text=AO",
    content:
      "That sounds perfect! What was the highlight of your trip? I'm especially hoping to see the Great Migration.",
    timestamp: "10:35 AM",
    type: "text",
    status: "read",
  },
  {
    id: "4",
    senderId: "me",
    content:
      "The Great Migration was absolutely breathtaking! We were there during the river crossing season. Seeing thousands of wildebeest and zebras crossing the Mara River was a once-in-a-lifetime experience. The guides knew exactly where to position us for the best views.",
    timestamp: "10:38 AM",
    type: "text",
    status: "read",
  },
  {
    id: "5",
    senderId: "other",
    senderName: "Amara Okafor",
    senderAvatar: "/placeholder.svg?height=40&width=40&text=AO",
    content: "Wow! That sounds incredible. How many days would you recommend for the full experience?",
    timestamp: "10:40 AM",
    type: "text",
    status: "read",
  },
  {
    id: "6",
    senderId: "me",
    content:
      "I'd recommend at least 4-5 days to really experience everything. We did a 5-day package and it was perfect - enough time to see different areas of the park and not feel rushed. Plus you get to witness different animal behaviors at various times of day.",
    timestamp: "10:42 AM",
    type: "text",
    status: "delivered",
  },
  {
    id: "7",
    senderId: "other",
    senderName: "Amara Okafor",
    senderAvatar: "/placeholder.svg?height=40&width=40&text=AO",
    content: "Thanks for the recommendation! The safari was absolutely amazing 🦁 The guides were so knowledgeable!",
    timestamp: "2 min ago",
    type: "text",
    status: "sent",
  },
]

// Enhanced notification data
export const mockNotifications = [
  {
    id: "1",
    type: "like" as const,
    title: "New Like",
    message: "Amara Okafor liked your post about Serengeti Safari experience",
    timestamp: "2 minutes ago",
    read: false,
    avatar: "/placeholder.svg?height=40&width=40&text=AO",
    actionUrl: "/post/1",
    userId: "user1",
  },
  {
    id: "2",
    type: "comment" as const,
    title: "New Comment",
    message: "Kwame Asante commented: 'Beautiful sculpture work! The Adinkra symbols are perfectly executed.'",
    timestamp: "15 minutes ago",
    read: false,
    avatar: "/placeholder.svg?height=40&width=40&text=KA",
    actionUrl: "/post/2",
    userId: "user2",
  },
  {
    id: "3",
    type: "follow" as const,
    title: "New Follower",
    message: "Zara Mwangi started following you",
    timestamp: "1 hour ago",
    read: false,
    avatar: "/placeholder.svg?height=40&width=40&text=ZM",
    actionUrl: "/profile/user3",
    userId: "user3",
  },
  {
    id: "4",
    type: "booking" as const,
    title: "Booking Confirmed",
    message: "Your hotel booking at Serengeti Safari Lodge has been confirmed for March 15-18",
    timestamp: "2 hours ago",
    read: true,
    actionUrl: "/bookings/booking1",
  },
  {
    id: "5",
    type: "message" as const,
    title: "New Message",
    message: "Atlas Mountain Tours sent you a message about your upcoming trek",
    timestamp: "3 hours ago",
    read: true,
    avatar: "/placeholder.svg?height=40&width=40&text=AMT",
    actionUrl: "/messages/4",
    userId: "business1",
  },
  {
    id: "6",
    type: "general" as const,
    title: "Tour Reminder",
    message: "Your Kilimanjaro trek starts tomorrow! Check your email for final preparations.",
    timestamp: "5 hours ago",
    read: true,
    actionUrl: "/tours/2",
  },
  {
    id: "7",
    type: "like" as const,
    title: "Post Popular",
    message: "Your post about Ethiopian coffee has reached 500 likes!",
    timestamp: "1 day ago",
    read: true,
    actionUrl: "/post/5",
  },
  {
    id: "8",
    type: "comment" as const,
    title: "New Comment",
    message: "Thandiwe Mthembu commented: 'This artwork speaks to my soul. Ubuntu philosophy beautifully expressed!'",
    timestamp: "1 day ago",
    read: true,
    avatar: "/placeholder.svg?height=40&width=40&text=TM",
    actionUrl: "/art/piece/1",
    userId: "artist1",
  },
]

// Additional mock data for enhanced demo
export const mockReviews = [
  {
    id: "1",
    userId: "user1",
    userName: "Amara Okafor",
    userAvatar: "/placeholder.svg?height=40&width=40&text=AO",
    rating: 5,
    comment:
      "Absolutely incredible experience! The guides were knowledgeable and the wildlife viewing was spectacular. Highly recommend!",
    timestamp: "2 weeks ago",
    helpful: 12,
  },
  {
    id: "2",
    userId: "user2",
    userName: "David Johnson",
    userAvatar: "/placeholder.svg?height=40&width=40&text=DJ",
    rating: 4,
    comment:
      "Great tour overall. The accommodation was comfortable and the food was excellent. Only minor issue was the early morning starts!",
    timestamp: "1 month ago",
    helpful: 8,
  },
  {
    id: "3",
    userId: "user3",
    userName: "Sarah Chen",
    userAvatar: "/placeholder.svg?height=40&width=40&text=SC",
    rating: 5,
    comment:
      "Life-changing experience! Seeing the Great Migration up close was beyond words. Professional service throughout.",
    timestamp: "2 months ago",
    helpful: 15,
  },
]

export const mockBookings = [
  {
    id: "booking1",
    type: "hotel",
    itemId: "1",
    itemName: "Serengeti Safari Lodge",
    checkIn: "2024-03-15",
    checkOut: "2024-03-18",
    guests: 2,
    totalPrice: 1140,
    status: "confirmed",
    bookingDate: "2024-02-15",
  },
  {
    id: "booking2",
    type: "tour",
    itemId: "2",
    itemName: "Kilimanjaro Trek - Machame Route",
    startDate: "2024-04-01",
    endDate: "2024-04-07",
    participants: 1,
    totalPrice: 1850,
    status: "pending",
    bookingDate: "2024-02-20",
  },
]
